# Generated by Django 3.1.1 on 2020-09-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('msrp', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
                ('purchase_link', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
