# Generated by Django 3.1.1 on 2020-09-10 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbb_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='kbb_backend.shoe')),
            ],
        ),
    ]
